version: "3.8"

services:
  registry:
    image: registry:2
    container_name: registry
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      REGISTRY_HTTP_ADDR: :5000
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: "Private Docker Registry"
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/emils-nuc-server.crt
      REGISTRY_HTTP_TLS_KEY: /certs/emils-nuc-server.key
    volumes:
      - ./auth:/auth
      - ./certs:/certs
      - ./data:/var/lib/registry
    networks:
      - core-network

networks:
  core-network:
    external: true
