version: "3.8"

services:
  vaultwarden:
    image: vaultwarden/server:1.33.2-alpine
    container_name: vaultwarden
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - ./data:/data
    networks:
      - core-network

networks:
  core-network:
    external: true
