version: "3.8"

services:
  mongodb:
    image: mongo:8.0.9
    container_name: mongodb
    hostname: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    env_file: ./.env
    volumes:
      - ./data:/data/db
    networks:
      - core-network

networks:
  core-network:
    external: true
