version: "3.8"

services:
  redis:
    image: redis:8.0.1
    container_name: redis
    restart: unless-stopped
    command: ["redis-server", "--loglevel", "warning", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"
    env_file: ./.env
    volumes: 
      - ./data:/data
    networks:
      - core-network

networks:
  core-network:
    external: true
